name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack (use package.json packageManager)
        run: corepack enable

      - name: Show tool versions
        run: |
          node -v
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck || pnpm tsc --noEmit

      - name: Lint
        run: pnpm lint || pnpm eslint .

      - name: Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'http://localhost:54321' }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'anon' }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY || 'service_role' }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET || 'devsecretdevsecretdevsecretdevsecret' }}
          NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || 'demo' }}
          DATABASE_URL: ${{ secrets.DATABASE_URL || 'postgres://postgres:postgres@localhost:5432/postgres' }}
          ADMIN_DATABASE_URL: ${{ secrets.ADMIN_DATABASE_URL || 'postgres://postgres:postgres@localhost:5432/postgres' }}
          DIRECT_URL: ${{ secrets.DIRECT_URL || 'postgres://postgres:postgres@localhost:5432/postgres' }}
        run: pnpm build
