name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Prepare pnpm from package.json's "packageManager" field (no jq needed)
      - name: Enable Corepack and activate pnpm
        run: |
          corepack enable
          PNPM_VERSION=$(node -p "require('./package.json').packageManager.split('@')[1]")
          echo "Using pnpm@$PNPM_VERSION"
          corepack prepare "pnpm@$PNPM_VERSION" --activate
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck || pnpm tsc --noEmit

      - name: Lint
        env:
          NEXT_DISABLE_ESLINT_PROMPT: '1'
        run: pnpm lint

      - name: Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'http://localhost:54321' }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'anon' }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY || 'service_role' }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET || 'devsecretdevsecretdevsecretdevsecret' }}
          NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || 'demo' }}
          DATABASE_URL: ${{ secrets.DATABASE_URL || 'postgres://postgres:postgres@localhost:5432/postgres' }}
          ADMIN_DATABASE_URL: ${{ secrets.ADMIN_DATABASE_URL || 'postgres://postgres:postgres@localhost:5432/postgres' }}
          DIRECT_URL: ${{ secrets.DIRECT_URL || 'postgres://postgres:postgres@localhost:5432/postgres' }}
        run: pnpm build
